// index.typ — editable entry point for your wiki.
// Compile this file with Typst to produce the full document.
//
// link.typ is auto-generated by zk-lsp and lists every note.
// Edit *this* file freely; do not edit link.typ by hand.

#import "include.typ": *
#import "zk/graph-view.typ": zk_knowledge_graph

#include "link.typ"
#context {
  let elements = query(metadata)
  let observations = zk_observations(elements)
  let graph-state = zk_graph_state(observations)
  let graph = graph-state.value
  let contents = zk_contents(elements)
  zk_knowledge_graph(graph-state)
  zk_present_nodes(
    graph,
    contents,
    reference-renderer: show-reference,
  )
}
